travis:
  secure:
    BINSTAR_TOKEN: d5Lodpw8w+RQpZAbKqkD9dDGWteGerLYsRJQ/fKLrv7ksrmeSQhx1QnJKyl8JXOSqI1vbSBRzoXNfLvZP+UtTpGiqvjMxgMeRw0eQtYUdFSFaGlyFXmroG/fdDAXbkx0HSYz+Vt7V+cmBrcoBvgDWbyqzDibj/DqhdG9KkkVsCZYVnqWNmGjZJQEDe1SMiUasDk2Ka3rGE+NXrsKcNlKu9JdZQa+/5n5TUKYzOopEpFDzL3G/gGSf3UcV9JFuqU0x/1mYlG6UqVUQb/Iq8fY4bWUmS8U3znUBKw5NZmITe+IpffUGMV8viWoaEWpUb9mILTTruIHoJPaqV8frplQMLGeXa3ol45dcBkdBO8zFfcKsbt1SVmbdarICcXzkaxwdB3wMkletjlmRS/lXo4rAewO4wEPSOHY/Mj0Ow5TjHKmGVCD9glj3Ye1f9uw5bjAFobYNKGsE5IiFkJJByCxHmpomDpdK1n6gAgcQtb9nXFh7LoXT/CWaLOaoVQEdEjbzAI4kE87T/Z9nKCbgG4QMR7inY+YiBkPNm+2ifUxJlak+vTGR5H5QsTZfPUwOwxMFarAS73N+1IWJHvB3qXkFKN3jMum/ls5E3U1/U9EP67+kap3/xuJqiP2RU5V7pEIss5g5JMnLgfTtmcO7Bus8gkfrFljQRqMlAKqiAB4ako=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
